name: Autograding

on:
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout student code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Checkout reference
        uses: actions/checkout@v4
        with:
          repository: RainDmitriy/AIE_matrix_lab
          token: ${{ secrets.REFERENCE_TOKEN }}
          path: reference

      - name: Check tests readiness
        run: |
          if [[ "${{ secrets.TESTS_READY }}" != "1" ]]; then
            echo "Тесты ещё не готовы для запуска. Попробуйте ещё раз после объявления от @raindmitriy об открытии тестов"
            exit 1
          else
            echo "Тесты доступны!"
          fi

      - name: Install dependencies
        run: pip install pytest

      - name: Run tests
        run: |
          echo "Запуск тестов"
          pytest reference/tests_base_operations.py --tb=short --maxfail=5
